/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cardboard.glb -t -s -T -k -r 
Files: cardboard.glb [4.6KB] > /Users/thib-cs/Work/Perso/project3D/threeJs-challenge-vending-machine/public/models/cardboard/cardboard-transformed.glb [2.05KB] (55%)
*/

import * as THREE from 'three'
import {useCubeTexture, useGLTF} from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane005: THREE.Mesh
    Plane005_1: THREE.Mesh
  }
  materials: {
    cardboard: THREE.MeshStandardMaterial
    cola: THREE.MeshStandardMaterial
  }
}


export function Cardboard(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/cardboard/cardboard-transformed.glb') as GLTFResult
  const envMap = useCubeTexture(
    ['px.png', 'nx.png', 'py.png', 'ny.png', 'pz.png', 'nz.png'],
    {path: '/envmap/cityNight/'}
  );

  const cardboardMaterial = materials.cardboard.clone();
  cardboardMaterial.envMap = envMap;
  cardboardMaterial.envMapIntensity = 5;

  const colaMaterial = materials.cola.clone();
  colaMaterial.envMap = envMap;
  colaMaterial.envMapIntensity = 5;
  return (
    <group {...props} dispose={null}>
      <mesh name="Plane005" castShadow receiveShadow geometry={nodes.Plane005.geometry} material={cardboardMaterial} />
      <mesh name="Plane005_1" castShadow receiveShadow geometry={nodes.Plane005_1.geometry} material={colaMaterial} />
    </group>
  )
}

useGLTF.preload('models/cardboard/cardboard-transformed.glb')
